Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=== RESTART: C:/Users/sai kumar mullapudi/Documents/python/Scraping/scrap2.py ==
[{'link': 'https://reperiendi.wordpress.com/2020/04/03/how-i-recovered-over-300k-of-bitcoin/',
  'title': 'How we recovered $300k of Bitcoin',
  'vote': 675},
 {'link': 'https://www.thevintagenews.com/2017/01/18/the-highest-paid-athlete-of-all-time-was-a-roman-charioteer-if-he-had-lived-today-he-would-have-been-worth-15-billion/',
  'title': 'The highest paid athlete of all time was a Roman Charioteer',
  'vote': 136},
 {'link': 'https://www.openttd.org/news/2020/04/01/openttd-1-10-0.html',
  'title': 'OpenTTD 1.10',
  'vote': 337},
 {'link': 'https://bernd.dev/2020/04/trim-videos-instantly/',
  'title': 'How to trim video clips instantly without reencoding',
  'vote': 108},
 {'link': 'https://hacks.mozilla.org/2020/04/twitter-direct-message-caching-and-firefox/',
  'title': 'Twitter Direct Message Caching and Firefox',
  'vote': 212},
 {'link': 'https://thinkfractional.blog/secret-ipad/',
  'title': 'Secret iPad',
  'vote': 372},
 {'link': 'https://robservatory.com/how-i-lost-control-of-our-bank-accounts-to-a-phone-scammer/',
  'title': 'How I lost control of our bank accounts to a phone scammer',
  'vote': 139},
 {'link': 'https://blogs.windows.com/windowsdeveloper/2020/03/19/hosted-app-model/',
  'title': 'Windows 10 Hosted App Model',
  'vote': 130},
 {'link': 'https://www.insidehook.com/article/bookshop-independent-bookstores-amazon',
  'title': 'Thanks to Bookshop, indies stand a chance against Amazon',
  'vote': 103},
 {'link': 'https://citizenlab.ca/2020/04/move-fast-roll-your-own-crypto-a-quick-look-at-the-confidentiality-of-zoom-meetings/',
  'title': 'Zoom rolled their own encryption scheme, transmit keys through '
           'servers in China',
  'vote': 899},
 {'link': 'https://amitness.com/2020/03/fixmatch-semi-supervised/',
  'title': 'Illustrated FixMatch for semi-supervised learning',
  'vote': 219},
 {'link': 'item?id=22773810',
  'title': 'Tell HN: Zoom runs application from Time Machine backup when '
           'uninstalled on Mac',
  'vote': 303},
 {'link': 'item?id=22769789',
  'title': 'I’m Peter Roberts, immigration attorney who does work for YC and '
           'startups. AMA',
  'vote': 188},
 {'link': 'https://github.com/capnmidnight/lozya',
  'title': 'Show HN: 2D Tilemap on Top of Jitsi Meet',
  'vote': 126},
 {'link': 'https://arstechnica.com/science/2020/04/spacex-loses-its-third-starship-prototype-during-a-cryogenic-test/',
  'title': 'SpaceX loses its third Starship prototype during a cryogenic test',
  'vote': 169},
 {'link': 'https://support.apple.com/guide/security/secbbd20b00b/1/web/1',
  'title': 'Hardware Microphone Disconnect in Mac and iPad',
  'vote': 716}]
>>> 